### ISSUE TITLE
Shader Composer 0.4.0 Roadmap

### ISSUE THREAD

**Issue by hmans** [hmans/composer-suite#196]
With Shader Composer being pretty much feature-complete with 0.3.0, the big theme for 0.4.0 is going to be **cleanup, restructuring, and documentation**:

#### Issues, PRs, Milestone links:

- https://github.com/hmans/composer-suite/milestone/2
- https://github.com/hmans/composer-suite/pull/244

#### Restructuring:

- [x] Brush up the structure of the stdlib modules, _maybe_ make them available as package entrypoints.
  - Note: we're not adding dedicated entrypoints at this point, but instead will (eventually, post-0.4) extract the individual standard library modules into micropackages.
- [ ] `shader-composer-toybox` should no longer exist. The functions that are generally useful, but a little too complex to live in core, should become their own packages (eg. `shader-composer-noise`.) Everything else should either move into `vfx-composer` or be removed.
- [ ] Maybe use the opportunity to move the individual packages into the `@shader-composer/*` namespace?

#### Documentation:

- [ ] Finally provide a decent README. It should contain a short example of what Shader Composer code looks like, and then redirect the user towards example sandboxes and vertical documentation.
- [ ] Have some sort of auto-generated documentation for units. I've experimented with using typedoc and markdown and it worked well. If we end up with micropackages for the different unit categories, each of them could have their own markdown file, and the main Shader Composer README could link to all of them.

**Comment by hmans** [comment]
Deprecating this issue in favor of individual issues assigned to milestones.
